version: '3.5'


services:

        mariadb:
                container_name: mariadb
                image: mariadb:custom
                networks:
                        - inception
                build:
                        context: requirements/mariadb
                        dockerfile: Dockerfile
                env_file:
                        - .env
                volumes:
                        - mariadb-v:/var/lib/mysql
                restart: on-failure

        nginx:
                container_name: nginx
                image: nginx:custom
                volumes:
                        - wordpress-v:/var/www/wordpress
                networks:
                        - inception
                depends_on:
                        - wordpress
                build:
                        context: requirements/nginx
                        dockerfile: Dockerfile
                ports:
                        - "443:443"
                restart: always

        wordpress:
                container_name: wordpress
                image: wordpress:custom
                env_file:
                        - .env
                volumes:
                        - wordpress-v:/var/www/wordpress
                networks:
                        - inception
                build:
                        context: requirements/wordpress
                        dockerfile: Dockerfile
                depends_on:
                        - mariadb
                restart: always
                expose:
                        - "9000"

networks:
        inception:
                driver: bridge
                name: inception
        
volumes:

        wordpress-v:
                name: wordpress-vo
                driver_opts:
                        type: 'none'
                        o: bind
                        device: '/home/fsariogl/data/wordpress'

        mariadb-v:
                name: mariadb-vo
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '/home/fsariogl/data/mariadb'
